name: CI Pipeline

on:
  push:
    branches: ["main", "testing"]
  pull_request:
    branches: ["main", "testing"]

jobs:
  lint:
    name: Code-Style & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Linting Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run Flake8 (Linting)
        run: |
          echo "Running Flake8..."
          flake8 --config=.flake8 --show-source --statistics .

      - name: Run Black (Code Formatting Check)
        run: |
          echo "Running Black..."
          black --check .

  test:
    name: Run Tests & Upload Coverage
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r frontend/requirements.txt || true  # Falls nicht nötig
          pip install -r model_training/requirements.txt || true
          pip install -r test/requirements.txt
          pip install pytest-cov

      - name: Run Pytest with Coverage
        run: |
          pytest --cov=backend --cov-report=xml test/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
