name: CI Pipeline

on:
  push:
    branches: ["main", "testing"]
  pull_request:
    branches: ["main", "testing"]

jobs:
  lint:
    name: Code-Style & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Linting Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 "black[jupyter]"==23.3.0 autoflake
          
      - name: Run Autoflake (Remove Unused Imports & Vars)
        run: |
          echo "Running autoflake..."
          autoflake --remove-all-unused-imports --remove-unused-variables --in-place --recursive backend


      - name: Run Black (Code Formatting Check)
        run: |
          echo "Running Black..."
          black .

      - name: Run Flake8 (Linting)
        run: |
          echo "Running Flake8..."
          flake8 --config=.flake8 --show-source --statistics .

  test:
    name: Run Tests & Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt
          pip install pytest-cov

      - name: Run Pytest with Coverage
        run: |
          pytest --cov=backend --cov-report=xml test/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
